export const API_CONFIG = {
  VAPI_API_KEY: process.env.NEXT_PUBLIC_VAPI_API_KEY || '',
  OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY || '',
  VAPI_PHONE_NUMBER: process.env.NEXT_PUBLIC_VAPI_PHONE_NUMBER || '+919876543210',
  OPENAI_MODEL: 'gpt-3.5-turbo',
  OPENAI_TEMPERATURE: 0.7,
  OPENAI_MAX_TOKENS: 150
} 